exclude:
  - node_modules
  - script

sass:
  style: compressed

remote_theme: pages-themes/primer

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

github:
  private: false
  license:
    name: MIT
  source:
    branch: "main"
    path: "/"
  repository_url: "https://github.com/bagustris/prophets"
  
title: Prophets
description: Genealogy and description of Prophets in Islam
