exclude:
  - node_modules
  - script

sass:
  style: compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "main"
    path: "/"
  repository_url: "https://github.com/bagustris/prophets"
  
title: Prophets
description: Genealogy and description of Prophets in Islam
