exclude:
  - node_modules
  - script
  - search-demo.html
  - "*.bak"
  - "*.nbak"
  - "Gemfile."
  - .specstory

sass:
  style: compressed

remote_theme: bagustris/primer2-theme

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

title: Prophets
description: Genealogy and description of Prophets in Islam

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

url: "https://bagustris.github.io"
baseurl: "/kisah-nabi"

github:
  repository_name: kisah-nabi
  repository_nwo: bagustris/kisah-nabi
  repository_url: "https://github.com/bagustris/kisah-nabi"
  owner_name: bagustris
